//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mascotas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class adoptante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adoptante()
        {
            this.adopcions = new HashSet<adopcion>();
        }
    
        public int idAdoptante { get; set; }
        public string nombreAdoptante { get; set; }
        public string direccionAdoptante { get; set; }
        public int telefono1Adoptante { get; set; }
        public int telefono2Adoptante { get; set; }
        public string emailAdoptante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adopcion> adopcions { get; set; }
    }
}
