//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mascotas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class adopcion
    {
        public int nroAdopcion { get; set; }
        public System.DateTime fechaAdopcion { get; set; }
        public int idAdoptante { get; set; }
        public int idMascota { get; set; }
    
        public virtual adoptante adoptante { get; set; }
        public virtual mascota mascota { get; set; }
    }
}
