//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mascotas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mascota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mascota()
        {
            this.adopcions = new HashSet<adopcion>();
        }
    
        public int idMascota { get; set; }
        public string nombreMascota { get; set; }
        public string edadMascota { get; set; }
        public string colorMascota { get; set; }
        public string generoMascota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adopcion> adopcions { get; set; }
    }
}
