//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mascotas.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class adopcionesEntities : DbContext
    {
        public adopcionesEntities()
            : base("name=adopcionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adopcion> adopcions { get; set; }
        public virtual DbSet<adoptante> adoptantes { get; set; }
        public virtual DbSet<mascota> mascotas { get; set; }
    }
}
