//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoTiendaWF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class videotiendaEntities : DbContext
    {
        public videotiendaEntities()
            : base("name=videotiendaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALQ_VIDEOJUEGOS> ALQ_VIDEOJUEGOS { get; set; }
        public virtual DbSet<ALQUILER> ALQUILERs { get; set; }
        public virtual DbSet<CAT_VIDEOJUEGOS> CAT_VIDEOJUEGOS { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIAS { get; set; }
        public virtual DbSet<DOMINIO> DOMINIOS { get; set; }
        public virtual DbSet<PERSONA> PERSONAS { get; set; }
        public virtual DbSet<PRODUCTORE> PRODUCTORES { get; set; }
        public virtual DbSet<VIDEOJUEGO> VIDEOJUEGOS { get; set; }
    }
}
